//! The engine seam (#255): what read-aloud (#256) needs from a TTS engine,
//! and the engine-independent parts — chunks in, audio out with the pauses
//! [`super::text`] asked for, and a WAV writer at the engine's rate.
//!
//! P18: generation to a file, not real-time playback, so an engine only
//! has to push audio as it goes; nothing here plays sound.

use super::text::Chunk;
use anyhow::{bail, Result};
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

/// A text-to-speech engine with one voice selected.
pub trait TtsEngine: Send {
    /// Sample rate of the audio it produces (Hz).
    fn sample_rate(&self) -> u32;

    /// Speak one piece of already prepared text (a [`Chunk`]'s text),
    /// handing the audio to `out` as it is produced. Stops with an error
    /// when `cancel` is set.
    fn speak(
        &mut self,
        text: &str,
        cancel: &AtomicBool,
        out: &mut dyn FnMut(&[f32]) -> Result<()>,
    ) -> Result<()>;
}

/// What a render produced.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct RenderStats {
    pub chunks: usize,
    /// Samples written, pauses included.
    pub samples: u64,
}

/// Speak `chunks` in order, each followed by its pause's silence (none
/// after the last one). `on_chunk(i, n)` is called before chunk `i` of
/// `n`. Blocking; stops with an error when `cancel` is set.
pub fn render(
    engine: &mut dyn TtsEngine,
    chunks: &[Chunk],
    cancel: &AtomicBool,
    on_chunk: &mut dyn FnMut(usize, usize),
    out: &mut dyn FnMut(&[f32]) -> Result<()>,
) -> Result<RenderStats> {
    let rate = engine.sample_rate();
    let mut stats = RenderStats::default();
    for (i, chunk) in chunks.iter().enumerate() {
        if cancel.load(Ordering::Relaxed) {
            bail!("reading cancelled");
        }
        on_chunk(i, chunks.len());
        if chunk.text.trim().is_empty() {
            continue;
        }
        engine.speak(&chunk.text, cancel, &mut |pcm| {
            stats.samples += pcm.len() as u64;
            out(pcm)
        })?;
        stats.chunks += 1;
        if i + 1 < chunks.len() {
            let n = (u64::from(chunk.pause_after.suggested_ms()) * u64::from(rate) / 1000) as usize;
            if n > 0 {
                out(&vec![0.0; n])?;
                stats.samples += n as u64;
            }
        }
    }
    Ok(stats)
}

/// What every file Sussurro speaks carries in its metadata (P21): the
/// `ICMT` comment of a WAV's `LIST/INFO` chunk. The watermark of E17 is
/// #264's.
pub const SYNTHETIC_COMMENT: &str = "Synthetic speech generated by Sussurro (Pocket TTS)";

/// A mono 16-bit PCM WAV at `rate` with a `LIST/INFO` chunk naming the
/// software and marking the audio as synthetic. Pure.
pub fn wav_bytes(rate: u32, samples: &[f32]) -> Vec<u8> {
    fn info(id: &[u8; 4], text: &str) -> Vec<u8> {
        let mut v = id.to_vec();
        let mut body = text.as_bytes().to_vec();
        body.push(0);
        if body.len() % 2 == 1 {
            body.push(0);
        }
        v.extend_from_slice(&(body.len() as u32).to_le_bytes());
        v.extend_from_slice(&body);
        v
    }
    let mut list = b"INFO".to_vec();
    list.extend(info(b"ISFT", "Sussurro"));
    list.extend(info(b"ICMT", SYNTHETIC_COMMENT));
    let data_len = (samples.len() * 2) as u32;
    let riff_len = 4 + (8 + 16) + (8 + list.len() as u32) + (8 + data_len);
    let mut out = Vec::with_capacity(riff_len as usize + 8);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&riff_len.to_le_bytes());
    out.extend_from_slice(b"WAVEfmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes()); // PCM
    out.extend_from_slice(&1u16.to_le_bytes()); // mono
    out.extend_from_slice(&rate.to_le_bytes());
    out.extend_from_slice(&(rate * 2).to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes());
    out.extend_from_slice(&16u16.to_le_bytes());
    out.extend_from_slice(b"LIST");
    out.extend_from_slice(&(list.len() as u32).to_le_bytes());
    out.extend_from_slice(&list);
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_len.to_le_bytes());
    for &s in samples {
        let v = (s.clamp(-1.0, 1.0) * i16::MAX as f32).round() as i16;
        out.extend_from_slice(&v.to_le_bytes());
    }
    out
}

/// Write [`wav_bytes`] to `path` (through a temporary file, then renamed).
pub fn write_wav(path: &Path, rate: u32, samples: &[f32]) -> Result<()> {
    let tmp = path.with_extension("wav.part");
    std::fs::write(&tmp, wav_bytes(rate, samples))?;
    std::fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::tts::text::Pause;

    /// Speaks every character as 10 samples of 0.5.
    pub(crate) struct FakeEngine {
        pub spoken: Vec<String>,
    }

    impl TtsEngine for FakeEngine {
        fn sample_rate(&self) -> u32 {
            1000
        }

        fn speak(
            &mut self,
            text: &str,
            cancel: &AtomicBool,
            out: &mut dyn FnMut(&[f32]) -> Result<()>,
        ) -> Result<()> {
            if cancel.load(Ordering::Relaxed) {
                bail!("cancelled");
            }
            self.spoken.push(text.to_string());
            out(&vec![0.5; text.chars().count() * 10])
        }
    }

    fn chunk(index: usize, text: &str, pause_after: Pause) -> Chunk {
        Chunk {
            index,
            text: text.into(),
            pause_after,
        }
    }

    #[test]
    fn chunks_are_spoken_in_order_with_their_pauses() {
        let mut e = FakeEngine { spoken: Vec::new() };
        let chunks = [
            chunk(0, "Ab.", Pause::Sentence), // 30 + 150 ms at 1 kHz
            chunk(1, "  ", Pause::Paragraph), // skipped, no pause
            chunk(2, "Cd.", Pause::Section),  // last: no pause after
        ];
        let mut audio = Vec::new();
        let mut seen = Vec::new();
        let stats = render(
            &mut e,
            &chunks,
            &AtomicBool::new(false),
            &mut |i, n| seen.push((i, n)),
            &mut |pcm| {
                audio.extend_from_slice(pcm);
                Ok(())
            },
        )
        .unwrap();
        assert_eq!(e.spoken, ["Ab.", "Cd."]);
        assert_eq!(seen, [(0, 3), (1, 3), (2, 3)]);
        assert_eq!(audio.len(), 30 + 150 + 30);
        assert_eq!(
            stats,
            RenderStats {
                chunks: 2,
                samples: 210
            }
        );
        assert!(audio[30..180].iter().all(|&s| s == 0.0));
    }

    #[test]
    fn a_cancelled_render_stops() {
        let mut e = FakeEngine { spoken: Vec::new() };
        let err = render(
            &mut e,
            &[chunk(0, "Ab.", Pause::None)],
            &AtomicBool::new(true),
            &mut |_, _| {},
            &mut |_| Ok(()),
        )
        .unwrap_err();
        assert!(err.to_string().contains("cancelled"));
        assert!(e.spoken.is_empty());
    }

    #[test]
    fn wav_has_the_rate_the_samples_and_the_synthetic_mark() {
        let wav = wav_bytes(24_000, &[0.0, 1.0, -1.0, 2.0]);
        let u32_at = |i: usize| u32::from_le_bytes(wav[i..i + 4].try_into().unwrap());
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(u32_at(4) as usize, wav.len() - 8);
        assert_eq!(&wav[8..16], b"WAVEfmt ");
        assert_eq!(u32_at(24), 24_000);
        let list = wav.windows(4).position(|w| w == b"LIST").unwrap();
        let data = wav.windows(4).position(|w| w == b"data").unwrap();
        assert!(list < data);
        let text = String::from_utf8_lossy(&wav[list..data]);
        assert!(text.contains(SYNTHETIC_COMMENT), "{text}");
        assert_eq!(u32_at(data + 4), 8);
        let pcm: Vec<i16> = wav[data + 8..]
            .chunks(2)
            .map(|b| i16::from_le_bytes([b[0], b[1]]))
            .collect();
        assert_eq!(pcm, [0, i16::MAX, -i16::MAX, i16::MAX], "clamped");
        // Every chunk has an even size, so the file is well formed.
        assert_eq!((data - list) % 2, 0);
    }
}
