//! Marking generated audio (P21, E17): **the one place** every audio file
//! Sussurro speaks passes through before it is written — the saved speech
//! of an item, the temporary *Listen* file (#256) and the Models → Voices
//! preview (#255).
//!
//! Two layers, as the plan asks:
//!
//! 1. **Metadata** (done here): the Ogg Opus comments of [`Marker::tags`]
//!    — `SYNTHETIC=1`, the generator, engine, voice, language and the IPTC
//!    digital source type `trainedAlgorithmicMedia` — plus, in the item's
//!    frontmatter, the `synthetic:` record of [`crate::archive::speech`]
//!    (its `marked:` list comes from [`Marker::marks`]). Previews are WAVs
//!    and carry the `LIST/INFO` comment of [`super::engine::wav_bytes`].
//! 2. **Watermark** (#257, not built yet): an inaudible AudioSeal mark on
//!    the PCM. [`Marker::process`] is the hook — every block of audio goes
//!    through it before it is encoded; today it leaves the samples as they
//!    are and [`Marker::marks`] does not claim a watermark. When #257 fills
//!    it in, `marks()` adds `"watermark"` and every new file records it.
//!
//! Nothing the app generates is ever presented as a recording: speech files
//! have their own names (`speech*.opus`, never `audio*`), the Audio tab
//! labels them "Generated speech", and the file says so itself.

/// Who made it.
pub const GENERATOR: &str = "Sussurro";
/// IPTC digital source type of AI-generated media (what the EU Code of
/// Practice on marking points to).
pub const DIGITAL_SOURCE_TYPE: &str =
    "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";
/// The `marked:` entry for the metadata layer.
pub const MARK_METADATA: &str = "metadata";
/// The `marked:` entry for the watermark layer (#257).
pub const MARK_WATERMARK: &str = "watermark";

/// What produced a piece of synthetic audio.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Provenance {
    /// "Pocket TTS".
    pub engine: String,
    /// Voice id.
    pub voice: String,
    /// Language code.
    pub language: String,
}

/// `Sussurro <version>`.
pub fn generator() -> String {
    format!("{GENERATOR} {}", env!("CARGO_PKG_VERSION"))
}

/// Marks one generated file (see the module docs).
#[derive(Debug, Clone)]
pub struct Marker {
    provenance: Provenance,
}

impl Marker {
    pub fn new(provenance: Provenance) -> Self {
        Self { provenance }
    }

    /// The Ogg Opus user comments every generated file carries.
    pub fn tags(&self) -> Vec<(String, String)> {
        let p = &self.provenance;
        vec![
            ("SYNTHETIC".into(), "1".into()),
            (
                "COMMENT".into(),
                format!("Synthetic speech generated by {GENERATOR} ({})", p.engine),
            ),
            ("ENCODER".into(), generator()),
            ("TTS_ENGINE".into(), p.engine.clone()),
            ("TTS_VOICE".into(), p.voice.clone()),
            ("LANGUAGE".into(), p.language.clone()),
            ("DIGITAL_SOURCE_TYPE".into(), DIGITAL_SOURCE_TYPE.into()),
        ]
    }

    /// **The watermark hook (#257).** Every block of generated audio, at
    /// `rate` Hz, passes through here before it is written, in order —
    /// 24 kHz for saved speech, *Listen* files (#309) and previews. #257's
    /// "M16" scheme (spike #240, E17) computes the mark on the 16 kHz
    /// resample of the block and adds it, upsampled, to the 24 kHz audio,
    /// so one 16 kHz detector reads every file. Not built yet: the samples
    /// are left as they are.
    pub fn process(&mut self, pcm: &mut [f32], rate: u32) {
        let _ = (pcm, rate);
    }

    /// The marks the files of this marker actually carry, for the
    /// frontmatter's `marked:` list.
    pub fn marks(&self) -> Vec<String> {
        vec![MARK_METADATA.to_string()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn marker() -> Marker {
        Marker::new(Provenance {
            engine: "Pocket TTS".into(),
            voice: "giovanni".into(),
            language: "it".into(),
        })
    }

    #[test]
    fn tags_say_the_audio_is_synthetic_and_who_made_it() {
        let tags = marker().tags();
        let get = |k: &str| tags.iter().find(|(n, _)| n == k).map(|(_, v)| v.as_str());
        assert_eq!(get("SYNTHETIC"), Some("1"));
        assert_eq!(get("DIGITAL_SOURCE_TYPE"), Some(DIGITAL_SOURCE_TYPE));
        assert_eq!(get("TTS_VOICE"), Some("giovanni"));
        assert!(get("ENCODER").unwrap().starts_with("Sussurro "));
        assert!(get("COMMENT").unwrap().contains("Synthetic speech"));
        // Vorbis comment names: printable ASCII 0x20–0x7D except '='.
        for (k, _) in &tags {
            assert!(
                k.bytes().all(|b| (0x20..=0x7d).contains(&b) && b != b'='),
                "{k}"
            );
        }
    }

    #[test]
    fn marks_claim_only_what_is_applied() {
        let mut m = marker();
        let mut pcm = vec![0.25f32; 16];
        m.process(&mut pcm, 24_000);
        assert_eq!(pcm, vec![0.25f32; 16], "no watermark until #257");
        assert_eq!(m.marks(), [MARK_METADATA]);
    }
}
