//! Marking generated audio (P21, E17): **the one place** every audio file
//! Sussurro speaks passes through before it is written — the saved speech
//! of an item, the temporary *Listen* file (#256) and the Models → Voices
//! preview (#255).
//!
//! Two layers, as the plan asks:
//!
//! 1. **Metadata**: the Ogg Opus comments of [`Marker::tags`] —
//!    `SYNTHETIC=1`, the generator, engine, voice, language and the IPTC
//!    digital source type `trainedAlgorithmicMedia` — plus, in the item's
//!    frontmatter, the `synthetic:` record of [`crate::archive::speech`]
//!    (its `marked:` list comes from [`Marker::marks`]). Previews are WAVs
//!    and carry the `LIST/INFO` comment of [`super::engine::wav_bytes`].
//!    Signed metadata (C2PA) is #257's second part, not built yet.
//! 2. **Watermark** (#257): an inaudible AudioSeal mark on the PCM, "M16"
//!    ([`super::watermark::M16`]). [`Marker::process`] is the hook — every
//!    block of audio goes through it before it is encoded, and
//!    [`Marker::finish`] returns the rest at the end. There is no switch:
//!    a [`Marker`] can't be made without the watermark model, so nothing is
//!    spoken when it is missing (fail closed).
//!
//! Nothing the app generates is ever presented as a recording: speech files
//! have their own names (`speech*.opus`, never `audio*`), the Audio tab
//! labels them "Generated speech", and the file says so itself.

use super::watermark::{WatermarkModel, M16};
use anyhow::Result;

/// Who made it.
pub const GENERATOR: &str = "Sussurro";
/// IPTC digital source type of AI-generated media (what the EU Code of
/// Practice on marking points to).
pub const DIGITAL_SOURCE_TYPE: &str =
    "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";
/// The `marked:` entry for the metadata layer.
pub const MARK_METADATA: &str = "metadata";
/// The `marked:` entry for the watermark layer (AudioSeal, #257).
pub const MARK_WATERMARK: &str = "watermark";

/// What produced a piece of synthetic audio.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Provenance {
    /// "Pocket TTS".
    pub engine: String,
    /// Voice id.
    pub voice: String,
    /// Language code.
    pub language: String,
}

/// `Sussurro <version>`.
pub fn generator() -> String {
    format!("{GENERATOR} {}", env!("CARGO_PKG_VERSION"))
}

/// Marks one generated file (see the module docs).
pub struct Marker {
    provenance: Provenance,
    m16: M16,
}

impl Marker {
    /// A marker for audio at `rate` Hz, watermarked by `watermark` (the
    /// AudioSeal generator in the app, [`super::watermark`]).
    pub fn new(provenance: Provenance, watermark: Box<dyn WatermarkModel>, rate: u32) -> Self {
        Self {
            provenance,
            m16: M16::new(watermark, rate),
        }
    }

    /// The Ogg Opus user comments every generated file carries.
    pub fn tags(&self) -> Vec<(String, String)> {
        let p = &self.provenance;
        vec![
            ("SYNTHETIC".into(), "1".into()),
            (
                "COMMENT".into(),
                format!("Synthetic speech generated by {GENERATOR} ({})", p.engine),
            ),
            ("ENCODER".into(), generator()),
            ("TTS_ENGINE".into(), p.engine.clone()),
            ("TTS_VOICE".into(), p.voice.clone()),
            ("LANGUAGE".into(), p.language.clone()),
            ("DIGITAL_SOURCE_TYPE".into(), DIGITAL_SOURCE_TYPE.into()),
        ]
    }

    /// **The watermark hook (#257).** Every block of generated audio, at
    /// the marker's rate (24 kHz for saved speech, *Listen* files and
    /// previews), passes through here in order before it is written; what
    /// comes back is the marked audio ready so far — later than it went in
    /// (up to 10 s wait for their watermark window), never reordered.
    /// [`Self::finish`] returns the rest. Errors (the model failing) must
    /// stop the file: nothing unmarked is written.
    pub fn process(&mut self, pcm: &[f32]) -> Result<Vec<f32>> {
        self.m16.push(pcm)
    }

    /// The rest of the marked audio, at the end of the file.
    pub fn finish(&mut self) -> Result<Vec<f32>> {
        self.m16.finish()
    }

    /// The marks the files of this marker carry, for the frontmatter's
    /// `marked:` list.
    pub fn marks(&self) -> Vec<String> {
        vec![MARK_METADATA.to_string(), MARK_WATERMARK.to_string()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tts::watermark::tests::FakeWatermark;

    fn marker() -> Marker {
        Marker::new(
            Provenance {
                engine: "Pocket TTS".into(),
                voice: "giovanni".into(),
                language: "it".into(),
            },
            FakeWatermark::boxed(),
            24_000,
        )
    }

    #[test]
    fn tags_say_the_audio_is_synthetic_and_who_made_it() {
        let tags = marker().tags();
        let get = |k: &str| tags.iter().find(|(n, _)| n == k).map(|(_, v)| v.as_str());
        assert_eq!(get("SYNTHETIC"), Some("1"));
        assert_eq!(get("DIGITAL_SOURCE_TYPE"), Some(DIGITAL_SOURCE_TYPE));
        assert_eq!(get("TTS_VOICE"), Some("giovanni"));
        assert!(get("ENCODER").unwrap().starts_with("Sussurro "));
        assert!(get("COMMENT").unwrap().contains("Synthetic speech"));
        // Vorbis comment names: printable ASCII 0x20–0x7D except '='.
        for (k, _) in &tags {
            assert!(
                k.bytes().all(|b| (0x20..=0x7d).contains(&b) && b != b'='),
                "{k}"
            );
        }
    }

    #[test]
    fn every_block_is_watermarked_and_both_marks_are_claimed() {
        let mut m = marker();
        let mut out = m.process(&[0.25f32; 16]).unwrap();
        out.extend(m.finish().unwrap());
        assert_eq!(out.len(), 16);
        assert!(out.iter().all(|&x| x != 0.25), "the watermark was added");
        assert_eq!(m.marks(), [MARK_METADATA, MARK_WATERMARK]);
    }
}
